@peopleDB.Server_HostAddress = http://localhost:5177

GET {{peopleDB.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{peopleDB.Server_HostAddress}}/api/users

###

POST {{peopleDB.Server_HostAddress}}/api/users
Content-Type: application/json
{
  "name": "John Doe",
  "email": "test@test.com",
  "password": "password"
}

###

@idGET=3
GET {{peopleDB.Server_HostAddress}}/api/users/{{idGET}}

###

@idPUT=1002
PUT {{peopleDB.Server_HostAddress}}/api/users/{{idPUT}}
Content-Type: application/json

{
  "name": "John Doe 2",
  "email": "test@test.com",
  "password": "password"
}

###
@idDELETE=1002
DELETE {{peopleDB.Server_HostAddress}}/api/users/{{idDELETE}}

###
