on:
  create:
    branches:
      - 'publishVue'
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    # needs: Publish
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      # uses: publishVue

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: site18627.siteasp.net
        username: site18627
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        server-dir: wwwroot/
        # local-dir: peopledb.client/dist
        # port: 1234 # todo replace with your web hosts ftps port
        exclude: |
                  **/.git*
                  **/.git*/**
                  **/node_modules/**
